version: "3.7"

services:
  flask:
    build: ./flask
    container_name: flask
    restart: always
    environment:
      APP_NAME: MyFlaskApp
    expose:
      - 8080
    links:
      - mongodb
      
  mongodb:
    image: mongo:4.0.8
    container_name: mongodb

  nginx:
    build: ./nginx
    container_name: nginx
    restart: always
    ports:
      - "80:80"